# -*- coding: utf-8 -*-
"""DOA and EEG-Classifier

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x53FwOX2RZ1AZAY_fcTkoHclpxroG8gG
"""

!pip install vitaldb
!pip install keras==3.6.0
!pip install tensorflow==2.18.0
!pip install scikit-learn==1.5.1
!pip install scikeras

import numpy as np
import pandas as pd
import scipy.signal
import matplotlib.pyplot as plt
import tensorflow as tf
import vitaldb
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Dropout, Conv1D, MaxPooling1D, GlobalMaxPooling1D, Input, Activation
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

import pandas as pd
SRATE = 128  # Sampling rate in Hz
SEGLEN = 4 * SRATE  # Segment length in samples (512 samples)
MAX_CASES = 100  # Maximum number of cases to process

# Read track and case information from VitalDB
df_trks = pd.read_csv("https://api.vitaldb.net/trks")
df_cases = pd.read_csv("https://api.vitaldb.net/cases")

# Define indices for the data columns
EEG = 0   # EEG data
SEVO = 1  # Sevoflurane concentration
BIS = 2   # Bispectral Index

# Select case IDs that meet inclusion criteria
caseids = set(df_cases.loc[df_cases['age'] > 18, 'caseid']) & \
          set(df_trks.loc[df_trks['tname'] == 'BIS/EEG1_WAV', 'caseid']) & \
          set(df_trks.loc[df_trks['tname'] == 'BIS/BIS', 'caseid']) & \
          set(df_trks.loc[df_trks['tname'] == 'Primus/EXP_SEVO', 'caseid'])

# Initialize lists to store data
x = []  # EEG data
y = []  # Adjusted Sevoflurane concentration (MAC)
b = []  # BIS values
c = []  # Case IDs
icase = 0  # Case counter

# Iterate through each case ID
for caseid in caseids:
    if icase >= MAX_CASES:
        break

    print(f'Loading case {caseid} ({icase + 1}/{MAX_CASES})...', end='', flush=True)

    # Exclude cases with certain anesthetic agents
    try:
        if np.any(vitaldb.load_case(caseid, 'Orchestra/PPF20_CE') > 0.2):
            print('Excluded: Propofol detected')
            continue
    except:
        pass

    try:
        if np.any(vitaldb.load_case(caseid, 'Primus/EXP_DES') > 1):
            print('Excluded: Desflurane detected')
            continue
    except:
        pass

    try:
        if np.any(vitaldb.load_case(caseid, 'Primus/FEN2O') > 2):
            print('Excluded: N2O detected')
            continue
    except:
        pass
    try:
        if np.any(vitaldb.load_case(caseid, 'Orchestra/RFTN50_CE') > 0.2):
            print('Excluded: Remifentanil detected')
            continue
    except:
        pass

    # Load EEG, Sevoflurane concentration, and BIS data
    try:
        vals = vitaldb.load_case(caseid, ['BIS/EEG1_WAV', 'Primus/EXP_SEVO', 'BIS/BIS'], 1 / SRATE)
    except:
        print('Failed to load data')
        continue

    if vals.shape[0] == 0:
        print('No data available')
        continue

 # Exclude cases where maximum SEVO concentration is less than 1
    if np.nanmax(vals[:, SEVO]) < 1:
        print('Excluded: All SEVO <= 1')
        continue

    # Get patient age and adjust Sevoflurane concentration based on age
    age = df_cases.loc[df_cases['caseid'] == caseid, 'age'].values[0]
    vals[:, SEVO] /= 1.80 * 10 ** (-0.00269 * (age - 40))

    # Check for valid BIS values
    if not np.any(vals[:, BIS] > 0):
        print('Excluded: All BIS <= 0')
        continue

    # Trim data to valid BIS indices
    valid_bis_idx = np.where(vals[:, BIS] > 0)[0]
    first_bis_idx = valid_bis_idx[0]
    last_bis_idx = valid_bis_idx[-1]
    vals = vals[first_bis_idx:last_bis_idx + 1, :]

    # Ensure data length is at least 30 minutes
    if len(vals) < 1800 * SRATE:
        print('Excluded: Data length less than 30 min')
        continue

    # Forward fill NaNs in SEVO and BIS columns
    df_vals = pd.DataFrame(vals[:, SEVO:], columns=['SEVO', 'BIS'])
    df_vals = df_vals.ffill(limit=5 * SRATE)
    vals[:, SEVO:] = df_vals.values

    oldlen = len(y)

    # Iterate over data to extract segments
    for irow in range(SEGLEN, len(vals), SRATE):
        bis = vals[irow, BIS]
        mac = vals[irow, SEVO]
        if np.isnan(bis) or np.isnan(mac) or bis == 0:
            continue

        eeg = vals[irow - SEGLEN:irow, EEG]
        if np.isnan(eeg).any():
            continue
        x.append(eeg)
        y.append(mac)
        b.append(bis)
        c.append(caseid)

    icase += 1
    print(f'{len(y) - oldlen} samples read, total {len(y)} samples')


# Convert lists to NumPy arrays
x = np.array(x)
y = np.array(y)
b = np.array(b)
c = np.array(c)

# Exclude invalid samples
print('Excluding invalid samples...', end='', flush=True)
valid_mask = ~np.isnan(x).any(axis=1)
valid_mask &= (np.nanmax(x, axis=1) - np.nanmin(x, axis=1) > 12)
valid_mask &= (np.nanmax(np.abs(x), axis=1) < 100)
x = x[valid_mask]
y = y[valid_mask]
b = b[valid_mask]
c = c[valid_mask]
print(f'{100 * (1 - np.mean(valid_mask)):.1f}% samples removed')

# Get unique case IDs
caseids = np.unique(c)

# Split data into training and testing sets (80% train, 20% test)
ntest = max(1, int(len(caseids) * 0.2))
caseids_test = caseids[:ntest]
caseids_train = caseids[ntest:]

train_mask = np.isin(c, caseids_train)
test_mask = np.isin(c, caseids_test)

x_train = x[train_mask]
y_train = y[train_mask]
x_test = x[test_mask]
y_test = y[test_mask]

b_train = b[train_mask]
b_test = b[test_mask]


c_test = c[test_mask]

print('====================================================')
print(f'Total: {len(caseids)} cases, {len(y)} samples')
print(f'Train: {len(np.unique(c[train_mask]))} cases, {len(y_train)} samples')
print(f'Test: {len(np.unique(c_test))} cases, {len(y_test)} samples')
print('====================================================')

###New code below: replaced y_train and y_test (mac values) with b_train and b_test (BIS aka DOA predictions)
y_train= b_train
y_test= b_test


# Reshape data for Conv1D input
x_train = x_train.reshape(-1, SEGLEN, 1)
x_test = x_test.reshape(-1, SEGLEN, 1)

## CLASSIFICATION
!pip install imbalanced-learn

from tensorflow.keras.utils import to_categorical
from imblearn.over_sampling import SMOTE
import numpy as np

def convert_to_categories(y):
    categories = []
    for value in y:
        if value < 40:
            categories.append(0)  # AD
        elif 40 <= value <= 60:
            categories.append(1)  # AO
        else:
            categories.append(2)  # AL
    return np.array(categories)

# Convert to categories without one-hot encoding
y_train_cat = convert_to_categories(y_train)
y_test_cat = convert_to_categories(y_test)

x_train_flat=x_train.reshape(x_train.shape[0], -1)

# Apply SMOTE to training data
smote = SMOTE(random_state=42)
x_train_resampled, y_train_resampled = smote.fit_resample(x_train_flat, y_train_cat)
x_train_resampled = x_train_resampled.reshape(-1, 512, 1)


# Convert to one-hot encoding after SMOTE
y_train_cat_balanced = to_categorical(y_train_resampled, num_classes=3)
y_test_cat = to_categorical(y_test_cat, num_classes=3)

from collections import Counter

print("Original class distribution:", Counter(y_train_cat))
print("Resampled class distribution:", Counter(y_train_resampled))

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, Bidirectional, GlobalAveragePooling1D
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import GridSearchCV


# Model creation function
def create_model(units=64, dropout=0.3):
    model = Sequential()
    model.add(LSTM(units,return_sequences=True))
    model.add(Dense(64, activation='relu'))
    model.add(Dropout(dropout))
    model.add(Bidirectional(LSTM(units, return_sequences=True)))
    model.add(GlobalAveragePooling1D())
    model.add(Dropout(dropout))
    model.add(Dense(100, activation='relu'))
    model.add(Dropout(dropout))
    model.add(Dense(64, activation='relu'))
    model.add(Dense(3, activation='softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model


# Define KerasRegressor
model = KerasClassifier(
    model=create_model,  # Use create_model function
    verbose=1
)

# Define parameter grid
param_grid = {
    'model__units': [40, 64],
    'model__dropout': [0.4, 0.5, 0.6],
    'batch_size': [100, 150, 200],
    'epochs': [10, 15]
}

# GridSearchCV
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1, cv=2)
grid_result = grid.fit(x_train_resampled, y_train_cat_balanced)

# Print results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_curve, auc
from sklearn.metrics import f1_score

def evaluate_model(model, x_test, y_test_cat):
    # Make predictions on the test set
    pred_class_test_prob = model.predict(x_test)
    pred_class_test = np.argmax(pred_class_test_prob, axis=1)

    # Convert y_test_cat back to class labels
    y_test_labels = np.argmax(y_test_cat, axis=1)

    # Evaluate the classification model
    accuracy = accuracy_score(y_test_labels, pred_class_test)
    print(f'Classification Accuracy: {accuracy:.4f}')

    # Confusion Matrix
    cm = confusion_matrix(y_test_labels, pred_class_test)
    print("Confusion Matrix:")
    print(cm)

    # Classification Report
    print("\nClassification Report:")
    print(classification_report(y_test_labels, pred_class_test, target_names=['AD', 'AO', 'AL']))

    # F1 Score (macro average)
    f1 = f1_score(y_test_labels, pred_class_test, average='macro')
    print(f"\nF1 Score (macro): {f1:.4f}")

    # ROC Curve and AUC for each class
    n_classes = 3
    fpr = dict()
    tpr = dict()
    roc_auc = dict()
    for i in range(n_classes):
        fpr[i], tpr[i], _ = roc_curve(y_test_cat[:, i], pred_class_test_prob[:, i])
        roc_auc[i] = auc(fpr[i], tpr[i])

    # Print AUC for each class
    for i in range(n_classes):
        print(f"AUC for class {i}: {roc_auc[i]:.4f}")

    import seaborn as sns

    # Confusion matrix heatmap
    plt.figure(figsize=(10, 8))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.title('Confusion Matrix')
    plt.show()

    return accuracy, cm, f1, roc_auc

from tensorflow import keras
from tensorflow.keras.layers import Input, RNN, LSTMCell, Dense, Dropout
from tensorflow.keras.layers import GlobalAveragePooling1D
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Bidirectional, LSTM

model = Sequential()
model.add(LSTM(64, return_sequences=True))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Bidirectional(LSTM(128, return_sequences=True)))
model.add(GlobalAveragePooling1D())
model.add(Dropout(0.4))
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.4))
model.add(Dense(64, activation='relu'))
model.add(Dense(3, activation='softmax'))  # 3 output classes

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(
    x_train_resampled, y_train_cat_balanced,
    validation_data=(x_test, y_test_cat),
    epochs=15,
    batch_size=126,
    callbacks=[
        ModelCheckpoint('model.keras', save_best_only=True),
       # EarlyStopping(patience=3, restore_best_weights=True)
    ]
)

# Evaluate the model
test_loss, test_accuracy = model.evaluate(x_test, y_test_cat)
print(f"Test accuracy: {test_accuracy}")
print(f"Test loss: {test_loss}")
print(f"  ")
print(f"  ")

evaluate_model(model, x_test, y_test_cat)