# -*- coding: utf-8 -*-
"""DOA and EEG Hyperparameter Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dA5SwqLKCeu7B97VWmjDLUbLWlt8Aj_x
"""

!pip install vitaldb
!pip install keras==3.6.0
!pip install tensorflow==2.18.0
!pip install scikit-learn==1.5.1
!pip install scikeras
import keras
import scikeras
import tensorflow
import sklearn

print(f"Keras version: {keras.__version__}")
print(f"SciKeras version: {scikeras.__version__}")
print(f"TensorFlow version: {tensorflow.__version__}")
print(f"scikit-learn version: {sklearn.__version__}")

import numpy as np
import pandas as pd
import scipy.signal
import matplotlib.pyplot as plt
import tensorflow as tf
import vitaldb
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Dropout, Conv1D, MaxPooling1D, GlobalMaxPooling1D, Input, Activation
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

SRATE = 128  # Sampling rate in Hz
SEGLEN = 4 * SRATE  # Segment length in samples (512 samples)
MAX_CASES = 100  # Maximum number of cases to process

# Read track and case information from VitalDB
df_trks = pd.read_csv("https://api.vitaldb.net/trks")
df_cases = pd.read_csv("https://api.vitaldb.net/cases")

# Define indices for the data columns
EEG = 0   # EEG data
SEVO = 1  # Sevoflurane concentration
BIS = 2   # Bispectral Index

# Select case IDs that meet inclusion criteria
caseids = set(df_cases.loc[df_cases['age'] > 18, 'caseid']) & \
          set(df_trks.loc[df_trks['tname'] == 'BIS/EEG1_WAV', 'caseid']) & \
          set(df_trks.loc[df_trks['tname'] == 'BIS/BIS', 'caseid']) & \
          set(df_trks.loc[df_trks['tname'] == 'Primus/EXP_SEVO', 'caseid'])

# Initialize lists to store data
x = []  # EEG data
y = []  # Adjusted Sevoflurane concentration (MAC)
b = []  # BIS values
c = []  # Case IDs
icase = 0  # Case counter

# Iterate through each case ID
for caseid in caseids:
    if icase >= MAX_CASES:
        break

    print(f'Loading case {caseid} ({icase + 1}/{MAX_CASES})...', end='', flush=True)

    # Exclude cases with certain anesthetic agents
    try:
        if np.any(vitaldb.load_case(caseid, 'Orchestra/PPF20_CE') > 0.2):
            print('Excluded: Propofol detected')
            continue
    except:
        pass

    try:
        if np.any(vitaldb.load_case(caseid, 'Primus/EXP_DES') > 1):
            print('Excluded: Desflurane detected')
            continue
    except:
        pass

    try:
        if np.any(vitaldb.load_case(caseid, 'Primus/FEN2O') > 2):
            print('Excluded: N2O detected')
            continue
    except:
        pass
    try:
        if np.any(vitaldb.load_case(caseid, 'Orchestra/RFTN50_CE') > 0.2):
            print('Excluded: Remifentanil detected')
            continue
    except:
        pass

    # Load EEG, Sevoflurane concentration, and BIS data
    try:
        vals = vitaldb.load_case(caseid, ['BIS/EEG1_WAV', 'Primus/EXP_SEVO', 'BIS/BIS'], 1 / SRATE)
    except:
        print('Failed to load data')
        continue

    if vals.shape[0] == 0:
        print('No data available')
        continue

 # Exclude cases where maximum SEVO concentration is less than 1
    if np.nanmax(vals[:, SEVO]) < 1:
        print('Excluded: All SEVO <= 1')
        continue

    # Get patient age and adjust Sevoflurane concentration based on age
    age = df_cases.loc[df_cases['caseid'] == caseid, 'age'].values[0]
    vals[:, SEVO] /= 1.80 * 10 ** (-0.00269 * (age - 40))

    # Check for valid BIS values
    if not np.any(vals[:, BIS] > 0):
        print('Excluded: All BIS <= 0')
        continue

    # Trim data to valid BIS indices
    valid_bis_idx = np.where(vals[:, BIS] > 0)[0]
    first_bis_idx = valid_bis_idx[0]
    last_bis_idx = valid_bis_idx[-1]
    vals = vals[first_bis_idx:last_bis_idx + 1, :]

    # Ensure data length is at least 30 minutes
    if len(vals) < 1800 * SRATE:
        print('Excluded: Data length less than 30 min')
        continue

    # Forward fill NaNs in SEVO and BIS columns
    df_vals = pd.DataFrame(vals[:, SEVO:], columns=['SEVO', 'BIS'])
    df_vals = df_vals.ffill(limit=5 * SRATE)
    vals[:, SEVO:] = df_vals.values

    oldlen = len(y)

    # Iterate over data to extract segments
    for irow in range(SEGLEN, len(vals), SRATE):
        bis = vals[irow, BIS]
        mac = vals[irow, SEVO]
        if np.isnan(bis) or np.isnan(mac) or bis == 0:
            continue

        eeg = vals[irow - SEGLEN:irow, EEG]
        if np.isnan(eeg).any():
            continue
        x.append(eeg)
        y.append(mac)
        b.append(bis)
        c.append(caseid)

    icase += 1
    print(f'{len(y) - oldlen} samples read, total {len(y)} samples')


# Convert lists to NumPy arrays
x = np.array(x)
y = np.array(y)
b = np.array(b)
c = np.array(c)

# Exclude invalid samples
print('Excluding invalid samples...', end='', flush=True)
valid_mask = ~np.isnan(x).any(axis=1)
valid_mask &= (np.nanmax(x, axis=1) - np.nanmin(x, axis=1) > 12)
valid_mask &= (np.nanmax(np.abs(x), axis=1) < 100)
x = x[valid_mask]
y = y[valid_mask]
b = b[valid_mask]
c = c[valid_mask]
print(f'{100 * (1 - np.mean(valid_mask)):.1f}% samples removed')

# Get unique case IDs
caseids = np.unique(c)

# Split data into training and testing sets (80% train, 20% test)
ntest = max(1, int(len(caseids) * 0.2))
caseids_test = caseids[:ntest]
caseids_train = caseids[ntest:]

train_mask = np.isin(c, caseids_train)
test_mask = np.isin(c, caseids_test)

x_train = x[train_mask]
y_train = y[train_mask]
x_test = x[test_mask]
y_test = y[test_mask]

b_train = b[train_mask]
b_test = b[test_mask]


c_test = c[test_mask]

print('====================================================')
print(f'Total: {len(caseids)} cases, {len(y)} samples')
print(f'Train: {len(np.unique(c[train_mask]))} cases, {len(y_train)} samples')
print(f'Test: {len(np.unique(c_test))} cases, {len(y_test)} samples')
print('====================================================')

###New code below: replaced y_train and y_test (mac values) with b_train and b_test (BIS aka DOA predictions)
y_train= b_train
y_test= b_test


# Reshape data for Conv1D input
x_train = x_train.reshape(-1, SEGLEN, 1)
x_test = x_test.reshape(-1, SEGLEN, 1)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, Bidirectional, GlobalAveragePooling1D
from scikeras.wrappers import KerasRegressor
from sklearn.model_selection import GridSearchCV

def create_model(units=64, dropout=0.3):
    model = Sequential()
    model.add(LSTM(units, return_sequences=True, input_shape=(SEGLEN, 1)))
    model.add(Dense(64, activation='relu'))
    model.add(Dropout(dropout))
    model.add(Bidirectional(LSTM(units, return_sequences=True)))
    model.add(GlobalAveragePooling1D())
    model.add(Dropout(dropout))
    model.add(Dense(100, activation='relu'))
    model.add(Dropout(dropout))
    model.add(Dense(32, activation='relu'))
    model.add(Dense(1))
    model.compile(loss='mean_absolute_error', optimizer='adam', metrics=['mean_absolute_error'])
    return model

# Define KerasRegressor
model = KerasRegressor(
    model=create_model,  # Use create_model function
    verbose=1
)
param_grid = {
    'model__units': [64, 100],
    'model__dropout': [0.6, 0.7],
    'batch_size': [150, 200, 250],
    'epochs': [10, 15]
}

grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1, cv=2)
grid_result = grid.fit(x_train, y_train)

print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))


means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, Bidirectional, GlobalAveragePooling1D
from scikeras.wrappers import KerasRegressor
from sklearn.model_selection import GridSearchCV


def create_model(units=64, dropout=0.3):
    model = Sequential()
    model.add(LSTM(units, return_sequences=True, input_shape=(SEGLEN, 1)))
    model.add(Dense(64, activation='relu'))
    model.add(Dropout(dropout))
    model.add(Bidirectional(LSTM(units, return_sequences=True)))
    model.add(GlobalAveragePooling1D())
    model.add(Dropout(dropout))
    model.add(Dense(128, activation='relu'))
    model.add(Dropout(dropout))
    model.add(Dense(64, activation='relu'))
    model.add(Dense(1))
    model.compile(loss='mean_absolute_error', optimizer='adam', metrics=['mean_absolute_error'])
    return model


# Define KerasRegressor
model = KerasRegressor(
    model=create_model,  # Use create_model function
    verbose=1
)
param_grid = {
    'model__units': [64, 100],
    'model__dropout': [0.6, 0.7],
    'batch_size': [150, 200, 250],
    'epochs': [10, 15]
}

grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1, cv=2)
grid_result = grid.fit(x_train, y_train)

print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))


means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))



import numpy as np
import scipy.signal
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score, mean_absolute_error

def analyze_model(model, x_test, y_test, c_test):
    # Make predictions on the test set
    pred_test = model.predict(x_test).flatten()

    for caseid in np.unique(c_test):
        case_mask = (c_test == caseid)
        pred_test[case_mask] = scipy.signal.medfilt(pred_test[case_mask], kernel_size=15)

    # Calculate Mean Absolute Error
    test_mae = mean_absolute_error(y_test, pred_test)
    print(f'Test MAE: {test_mae}')

    # Calculate correlation coefficient and R-squared
    corr = np.corrcoef(y_test, pred_test)[0, 1]
    r2 = r2_score(y_test, pred_test)
    print(f'Correlation coefficient: {corr}')
    print(f'R squared: {r2}')

    # Scatter plot of actual vs. predicted DOA values
    plt.figure(figsize=(6, 6))
    plt.scatter(y_test, pred_test, s=1, alpha=0.5, color='violet')
    plt.xlabel('Actual DOA')
    plt.ylabel('Predicted DOA')
    plt.title(f'Scatter Plot (Correlation: {corr:.4f})')
    plt.plot([0, 2], [0, 2], 'r--')
    plt.xlim([0, 2])
    plt.ylim([0, 2])
    plt.show()

      # Plot predictions for random test cases
    for caseid in np.random.choice(np.unique(c_test), size=3, replace=False):
        case_mask = (c_test == caseid)
        case_len = np.sum(case_mask)
        if case_len == 0:
            continue
        our_mae = np.mean(np.abs(y_test[case_mask] - pred_test[case_mask]))
        t = np.arange(case_len)
        plt.figure(figsize=(10, 4))
        plt.plot(t, y_test[case_mask], label='Actual DOA')
        plt.plot(t, pred_test[case_mask], label=f'Predicted DOA (DOA: {our_mae:.4f})')
        plt.legend()
        plt.xlabel('Time')
        plt.ylabel('DOA')
        plt.title(f'Case {caseid}')
        plt.show()
        print(f'Case {caseid}, DOA: {our_mae:.4f}')

#LSTM--- works (tested)

from tensorflow import keras
from tensorflow.keras.layers import Input, RNN, LSTMCell, Dense, Dropout
from tensorflow.keras.layers import GlobalAveragePooling1D
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Bidirectional, LSTM

model = Sequential()
model.add(LSTM(64,return_sequences=True))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.3))
model.add(Bidirectional(LSTM(64, return_sequences=True)))
model.add(GlobalAveragePooling1D())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.4))
model.add(Dense(64))
model.add(Dense(1))
model.compile(loss='mean_absolute_error', optimizer='adam', metrics=['mean_absolute_error'])

model.fit(
    x_train, y_train,
    validation_data=(x_test, y_test),
    epochs=10,
    batch_size=256,
    callbacks=[
        ModelCheckpoint('model.keras', save_best_only=True),
        EarlyStopping(patience=3, restore_best_weights=True)
    ]
)

test_mae, test_accuracy = model.evaluate(x_test, y_test)
print(f"Test accuracy: {test_accuracy}")
print(f"Test MAE: {test_mae}")

analyze_model(model, x_test, y_test, c_test)

test_model = Sequential()
test_model.add(LSTM(64,return_sequences=True))
test_model.add(Dense(64, activation='relu'))
test_model.add(Dropout(0.5))
test_model.add(Bidirectional(LSTM(128, return_sequences=True)))
test_model.add(GlobalAveragePooling1D())
test_model.add(Dropout(0.7))
test_model.add(Dense(64, activation='relu'))
test_model.add(Dropout(0.5))
test_model.add(Dense(64, activation='relu'))
test_model.add(Dense(1))
test_model.compile(loss='mean_absolute_error', optimizer='adam', metrics=['mean_absolute_error'])

test_model.fit(
    x_train, y_train,
    validation_data=(x_test, y_test),
    epochs=15,
    batch_size=256,
    callbacks=[
        ModelCheckpoint('model.keras', save_best_only=True),
        EarlyStopping(patience=3, restore_best_weights=True)
    ]
)

test_mae, test_accuracy = test_model.evaluate(x_test, y_test)
print(f"Test accuracy: {test_accuracy}")
print(f"Test MAE: {test_mae}")
print(f"    ")
print(f"    ")
analyze_model(test_model, x_test, y_test, c_test)